// File generated by FlutterFire CLI or manually configured
// You need to replace these values with your Firebase project config
// Get them from: Firebase Console → Project Settings → Your apps → Web app

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAX8jtBzpxGXY3ZVRo8_PGB8YhzTCIQGwY",
    authDomain: "project-connect-dc6ae.firebaseapp.com",
    projectId: "project-connect-dc6ae",
    storageBucket: "project-connect-dc6ae.firebasestorage.app",
    messagingSenderId: "1031987338127",
    appId: "1:1031987338127:web:e8d15041c4b6f0a77389fa",
    measurementId: "G-Y3NW5NFRX2",
  );
}
